custom_css:
    cursor:
        enable: true
        text: volantis-static/media/cursor/text.png # https://gcore.jsdelivr.net/gh/inkss/common@1/cursor/text.png
        pointer: volantis-static/media/cursor/pointer.png # https://gcore.jsdelivr.net/gh/inkss/common@1/cursor/pointer.png
        default: volantis-static/media/cursor/left_ptr.png # https://gcore.jsdelivr.net/gh/inkss/common@1/cursor/left_ptr.png
        not-allowed: volantis-static/media/cursor/circle.png # https://gcore.jsdelivr.net/gh/inkss/common@1/cursor/circle.png
        zoom-out: volantis-static/media/cursor/zoom-out.png # https://gcore.jsdelivr.net/gh/inkss/common@1/cursor/zoom-out.png
        zoom-in: volantis-static/media/cursor/zoom-in.png # https://gcore.jsdelivr.net/gh/inkss/common@1/cursor/zoom-in.png
        grab: volantis-static/media/cursor/openhand.png # https://gcore.jsdelivr.net/gh/inkss/common@1/cursor/openhand.png
############################### Navigation Bar ############################### > start
# 注意事项：建议规范全站路径 URL 最后带一个 "/" 例如 "about/"
navbar:
    visiable: auto # always, auto
    logo: # choose [img] or [icon + title]
        img: https://lululu.online/images/navbarLogo.jpg
        icon:
        title:
    menu:
        - name: 博客
          icon: fa-solid fa-rss
          url: /
        - name: 分类
          icon: fa-solid fa-folder-open
          url: categories/
        - name: 标签
          icon: fa-solid fa-tags
          url: tags/
        - name: 归档
          icon: fa-solid fa-archive
          url: archives/
        - name: 友链
          icon: fa-solid fa-link
          url: friends/
        - name: 关于
          icon: fa-solid fa-info-circle
          url: about/
    search: Search... # Search bar placeholder
############################### Navigation Bar ############################### > end
